@startuml
title Диаграмма вариантов использования сайта РГЭУ(РИНХ)

' left to right direction
usecase "Администрирование" as UC1

' Обявление актеров
actor "Админиcтратор" as admin

admin <|-- employee


@enduml