@startuml
title Диаграмма вариантов использования сайта РГЭУ(РИНХ)

' left to right direction

' Обявление актеров
actor "Сотрудник" as employee
actor "Абитуриент" as entrant
actor "Выпускник" as graduate
actor "Преподователь" as teacher
actor "Бакалавр" as bachelor
actor "Магистр" as master
actor "Аспирант" as graduate_student

' user <|-- employee
' user <|-- entrant
' user <|-- student
' user <|-- graduate
' student <|-- bachelor
' student <|-- master
' student <|-- graduate_student



usecase "Просмотр нормативных документов" as UC1
usecase "Просмотр медиа контента" as UC5
usecase "Просмотр информации\n для студентов" as UC2
usecase "Просмотр информации\n о структурных подразделениях" as UC6
usecase "Использование подсистемы\n расписания" as UC7

UC1 <|-- bachelor
UC1 <|-- master
UC1 <|-- graduate_student
UC1 <|-- employee
UC1 <|-- entrant

UC2 <|-- master

@enduml